CREATE TABLE IF NOT EXISTS Pics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    page_id INTEGER NOT NULL,
    filename TEXT NOT NULL,
    caption TEXT DEFAULT NULL,
    sequence INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (page_id) REFERENCES Pages(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pics_page_id ON Pics(page_id);